project_name: midas

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod tidy

builds:
  - id: "midasd"
    main: ./cmd/midasd
    binary: midasd
    goos:
      - linux
      - windows
      - darwin

archives:
  - id: midasd
    builds:
      - midasd
    wrap_in_directory: "true"
    format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{- .ProjectName }}_
      {{- .Version }}_
      {{- if eq .Os "darwin" }}mac{{ else }}{{ .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- if eq .Arch "386" }}i386

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc

release:
  github:
    owner: kovansky
    name: midas
  ids:
    - midasd
  header: |
    ## Midas v{{ .Version }} ({{ .Date }})
  name_template: "{{ .ProjectName }} v{{ .Version }}"
