name: Test project

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install go
        uses: actions/setup-go@v2
        with:
          go-version: "^1.17"
      - name: Build
        run: go build -v ./...
      - name: Run tests
        run: go test -v ./...
